name: build
on: [push]

jobs:
  build-main:
    runs-on: self-hosted
    container:
      image: adnrv/texlive:adntools
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile PDF
        run: |
          latexmk -pdf --shell-escape  ${{ vars.FILE_TEX }}
      - name: Move
        run: mkdir -p artifacts && mv ${{ vars.FILE_PDF }} ./artifacts/
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts/${{ vars.FILE_PDF }}

